name: JoinMusik
authors:
  - T0biii
  - Fruxz
depend: [NoteBlockAPI]
version: '2.2'
website: http://dev.bukkit.org/bukkit-plugins/joinmusik

main: de.t0biii.musik.main.Main
database: false
commands:
  JoinMusik:
    description: /PlayMusik
    aliases: [jm, joinmusic]
