name: JoinMusik
author: T0biii
depend: [NoteBlockAPI]
version: 2.2
website: http://dev.bukkit.org/bukkit-plugins/joinmusik

main: de.t0biii.musik.JoinMusic
database: false
commands:
  JoinMusik:
    description: /PlayMusik
    aliases: [jm, joinmusic]
