site_name: JoinMusic
site_description: A Bukkit/Spigot plugin that plays music when a player joins the server
site_author: T0biii
repo_url: https://github.com/T0biii/JoinMusic
repo_name: T0biii/JoinMusic
theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true

nav:
  - Home: index.md
  - Features: features.md
  - Installation: installation.md
  - Configuration: configuration.md
  - Commands: commands.md
  - Permissions: permissions.md
  - Statistics: statistics.md 
