name: JoinMusic
authors:
- T0biii
- Fruxz
depend:
- NoteBlockAPI
version: '2.2'
website: http://dev.bukkit.org/bukkit-plugins/joinmusik
main: de.t0biii.music.main.Main
database: false
commands:
   JoinMusic:
      description: /JoinMusic
      usage: /<command> [reload]
      aliases:
      - jm
      - joinmusic
      - joinmusik
      permission: JoinMusik.command.reload