name: JoinMusic
authors:
  - T0biii
  - Fruxz
  - altrisi
depend:
  - NoteBlockAPI
softdepend:
  - PlaceholderAPI
version: ${project.version}
website: https://modrinth.com/plugin/joinmusic
main: de.t0biii.joinmusic.spigot.main.Main
database: false
commands:
  JoinMusic:
    description: /JoinMusic
    usage: /<command> [reload | stop | enable | disable]
    aliases:
      - jm
      - joinmusic
      - joinmusik
permissions:
  JoinMusic.command.reload:
    description: Allows reloading configs
    default: op
  JoinMusic.update:
    description: Will get info about updates
    default: op
  JoinMusic.command.stop:
    description: Allows stopping music from playing
    default: true
  JoinMusic.command.disableOwn:
    description: Allows disabling music on join for themself
    default: true
  JoinMusic.use:
    description: Allows the user to hear the music on join and access the command
    default: true
api-version: 1.13
